OPERATOR_MODES = (
    "research_operator",
    "content_operator",
    "leadgen_operator",
    "product_operator",
)

MODE_PROMPTS = {
    "research_operator": {
        "label": "Research Operator",
        "guidance": (
            "Identify profitable research, analysis, and intelligence offers that can start as a service "
            "and later become a product."
        ),
        "fallback": {
            "niche": "B2B competitive intelligence for service businesses",
            "target_customer": "Boutique agencies and consulting firms",
            "core_problem": "Teams need faster market insight without hiring full-time analysts",
            "offer": "Recurring competitor and market brief service",
            "mvp": "Weekly insight dashboard with manual analyst review",
            "distribution_channel": "Founder-led outbound to agency owners",
            "monetization_model": "Monthly retainer with setup fee",
            "opportunity_score": 8,
            "confidence_score": 7,
            "reasoning": (
                "The problem is expensive, recurring, and easy to validate with service-led delivery before "
                "building software."
            ),
            "next_actions": [
                "Interview five agency owners about research bottlenecks",
                "Package a sample weekly intelligence brief",
                "Pitch a paid pilot to one niche agency segment",
            ],
            "deliverables": [
                "Sample insight report",
                "Pilot scope document",
                "Outreach list of ideal buyers",
            ],
        },
        "fallback_opportunities": [
            {
                "title": "Competitive Intelligence Briefing Service",
                "niche": "B2B competitive intelligence for service businesses",
                "target_customer": "Boutique agencies and consulting firms",
                "core_problem": "Teams need faster market insight without hiring full-time analysts",
                "offer": "Recurring competitor and market brief service",
                "mvp": "Weekly insight dashboard with manual analyst review",
                "distribution_channel": "Founder-led outbound to agency owners",
                "monetization_model": "Monthly retainer with setup fee",
                "opportunity_score": 8,
                "confidence_score": 7,
                "reasoning": "The problem is expensive, recurring, and easy to validate with service-led delivery before building software.",
                "next_actions": [
                    "Interview five agency owners about research bottlenecks",
                    "Package a sample weekly intelligence brief",
                    "Pitch a paid pilot to one niche agency segment",
                ],
                "deliverables": [
                    "Sample insight report",
                    "Pilot scope document",
                    "Outreach list of ideal buyers",
                ],
            },
            {
                "title": "Vertical Market Sizing Sprint",
                "niche": "Rapid market sizing for niche B2B operators",
                "target_customer": "Solo founders and small private equity scouts",
                "core_problem": "Operators waste weeks validating niche demand manually",
                "offer": "Two-week market sizing and buyer signal sprint",
                "mvp": "Analyst-led market map with buyer interviews and TAM snapshot",
                "distribution_channel": "LinkedIn outbound and niche founder communities",
                "monetization_model": "Fixed-fee sprint",
                "opportunity_score": 7,
                "confidence_score": 7,
                "reasoning": "Fast validation work is a strong wedge service and can later become a software-enabled research workflow.",
                "next_actions": [
                    "Package one sample niche sizing report",
                    "Create a clear sprint offer page",
                    "Reach out to founders already exploring adjacent markets",
                ],
                "deliverables": [
                    "Sample TAM report",
                    "Sprint offer page",
                    "Prospect list",
                ],
            },
            {
                "title": "Voice-of-Customer Insight Studio",
                "niche": "Customer interview synthesis for SaaS teams",
                "target_customer": "Seed and Series A SaaS founders",
                "core_problem": "Teams collect user feedback but fail to turn it into clear strategic direction",
                "offer": "Monthly voice-of-customer synthesis subscription",
                "mvp": "Interview transcript clustering and recommendation summary",
                "distribution_channel": "Founder referrals and product-led newsletters",
                "monetization_model": "Monthly subscription",
                "opportunity_score": 7,
                "confidence_score": 6,
                "reasoning": "Customer research is high value and recurring, with a credible path from manual service into productized workflow tooling.",
                "next_actions": [
                    "Create a sample VOC synthesis report",
                    "Identify SaaS founders already doing customer calls",
                    "Offer a discounted first-month pilot",
                ],
                "deliverables": [
                    "VOC sample deck",
                    "Founder outreach script",
                    "Pilot pricing memo",
                ],
            },
            {
                "title": "Procurement Signal Watchlist",
                "niche": "Research alerts for enterprise procurement changes",
                "target_customer": "Revenue teams selling into enterprise accounts",
                "core_problem": "Teams miss buying-window signals buried in public data and contracts",
                "offer": "Weekly procurement intelligence alert service",
                "mvp": "Tracked account watchlist with change alerts and buying notes",
                "distribution_channel": "Targeted outbound to B2B sales leaders",
                "monetization_model": "Monthly retainer",
                "opportunity_score": 6,
                "confidence_score": 6,
                "reasoning": "The pain is real and revenue-linked, but data quality risk is slightly higher than simpler research offers.",
                "next_actions": [
                    "Prototype one procurement watchlist report",
                    "Validate the data sources for alert quality",
                    "Pitch three sales teams with named target accounts",
                ],
                "deliverables": [
                    "Watchlist prototype",
                    "Source quality checklist",
                    "Sales outreach deck",
                ],
            },
            {
                "title": "M&A Target Discovery Desk",
                "niche": "Deal-sourcing research for small acquirers",
                "target_customer": "Micro-PE firms and acquisition entrepreneurs",
                "core_problem": "Buyers struggle to systematically surface promising small acquisition targets",
                "offer": "AI-assisted acquisition target discovery service",
                "mvp": "Ranked target list with quick commercial notes",
                "distribution_channel": "Operator communities and niche M&A newsletters",
                "monetization_model": "Project fee plus success retainer",
                "opportunity_score": 6,
                "confidence_score": 5,
                "reasoning": "The value per client is high, but sales cycles are slower and proof requirements are stronger.",
                "next_actions": [
                    "Build a sample acquisition target list",
                    "Identify the best acquisition-entrepreneur communities",
                    "Test a concierge sourcing offer with two buyers",
                ],
                "deliverables": [
                    "Target list sample",
                    "Community channel list",
                    "Concierge offer brief",
                ],
            },
        ],
    },
    "content_operator": {
        "label": "Content Operator",
        "guidance": (
            "Identify profitable content, newsletter, media, or content-production opportunities with fast "
            "distribution and monetization."
        ),
        "fallback": {
            "niche": "Niche B2B content engine for regulated service industries",
            "target_customer": "Small firms in finance, legal, and compliance-heavy sectors",
            "core_problem": "Firms need consistent expert content but lack production capacity",
            "offer": "AI-assisted authority content subscription",
            "mvp": "Monthly content package with briefs, drafts, and distribution calendar",
            "distribution_channel": "LinkedIn content plus outbound email",
            "monetization_model": "Monthly subscription",
            "opportunity_score": 7,
            "confidence_score": 6,
            "reasoning": (
                "Content demand is steady, delivery is lightweight, and a service wrapper makes early sales easier "
                "than launching a pure media brand."
            ),
            "next_actions": [
                "Choose one niche with expensive customer acquisition",
                "Create three sample authority posts and one newsletter",
                "Offer a low-friction first-month content pilot",
            ],
            "deliverables": [
                "Editorial calendar",
                "Three post templates",
                "Pilot pricing sheet",
            ],
        },
        "fallback_opportunities": [
            {
                "title": "Authority Content Subscription",
                "niche": "Niche B2B content engine for regulated service industries",
                "target_customer": "Small firms in finance, legal, and compliance-heavy sectors",
                "core_problem": "Firms need consistent expert content but lack production capacity",
                "offer": "AI-assisted authority content subscription",
                "mvp": "Monthly content package with briefs, drafts, and distribution calendar",
                "distribution_channel": "LinkedIn content plus outbound email",
                "monetization_model": "Monthly subscription",
                "opportunity_score": 7,
                "confidence_score": 6,
                "reasoning": "Content demand is steady, delivery is lightweight, and a service wrapper makes early sales easier than launching a pure media brand.",
                "next_actions": [
                    "Choose one niche with expensive customer acquisition",
                    "Create three sample authority posts and one newsletter",
                    "Offer a low-friction first-month content pilot",
                ],
                "deliverables": [
                    "Editorial calendar",
                    "Three post templates",
                    "Pilot pricing sheet",
                ],
            },
            {
                "title": "Industry Newsletter Growth Studio",
                "niche": "Niche email media for overlooked B2B operators",
                "target_customer": "Founders and operators in fragmented service industries",
                "core_problem": "Professionals need curated industry insight but lack a trusted content source",
                "offer": "Curated newsletter with premium sponsor and membership upsell",
                "mvp": "Weekly niche newsletter with one sponsored slot and downloadable brief",
                "distribution_channel": "Newsletter swaps and LinkedIn distribution",
                "monetization_model": "Sponsorship plus premium membership",
                "opportunity_score": 7,
                "confidence_score": 6,
                "reasoning": "Media businesses are slower to build, but niche trust plus multiple monetization paths can create a durable asset.",
                "next_actions": [
                    "Pick one underserved industry niche",
                    "Write three pilot newsletter issues",
                    "Line up two potential sponsors for early conversations",
                ],
                "deliverables": [
                    "Pilot issue drafts",
                    "Sponsor deck",
                    "Audience growth plan",
                ],
            },
            {
                "title": "Repurposed Founder Content Engine",
                "niche": "Done-for-you founder thought leadership",
                "target_customer": "Consultants and agency founders with strong expertise but limited time",
                "core_problem": "Experts need a content presence but cannot publish consistently",
                "offer": "Interview-to-content repurposing service",
                "mvp": "One monthly founder interview turned into posts, newsletter, and short clips",
                "distribution_channel": "Warm outbound and referral partnerships",
                "monetization_model": "Monthly retainer",
                "opportunity_score": 8,
                "confidence_score": 7,
                "reasoning": "This is close to pain, easy to sell, and can later expand into a software workflow for content transformation.",
                "next_actions": [
                    "Package a founder content transformation sample",
                    "Create before-and-after content case studies",
                    "Offer a paid pilot to founders already posting inconsistently",
                ],
                "deliverables": [
                    "Sample repurposed content bundle",
                    "Case study one-pager",
                    "Pilot offer email",
                ],
            },
            {
                "title": "SEO Briefing Content Desk",
                "niche": "SEO content planning for high-ticket service firms",
                "target_customer": "Small B2B firms with long sales cycles",
                "core_problem": "Teams publish content without a clear search opportunity map",
                "offer": "AI-assisted SEO briefing and editorial planning service",
                "mvp": "Monthly keyword and article brief package",
                "distribution_channel": "Search consultants and outbound partnerships",
                "monetization_model": "Subscription or retainer",
                "opportunity_score": 6,
                "confidence_score": 6,
                "reasoning": "SEO demand is clear, but the market is crowded and differentiation depends on vertical specialization.",
                "next_actions": [
                    "Choose one vertical where search matters commercially",
                    "Produce a sample content brief packet",
                    "Partner with one SEO freelancer for referrals",
                ],
                "deliverables": [
                    "Keyword packet",
                    "Brief template",
                    "Referral pitch deck",
                ],
            },
            {
                "title": "Customer Story Media Service",
                "niche": "Case-study and testimonial content production",
                "target_customer": "B2B SaaS and service firms with weak proof assets",
                "core_problem": "Teams need strong proof-based content but struggle to capture and package customer wins",
                "offer": "Customer story production subscription",
                "mvp": "Monthly case study interview, write-up, and social asset pack",
                "distribution_channel": "Customer marketing teams and founder outbound",
                "monetization_model": "Retainer plus asset bundle upsells",
                "opportunity_score": 7,
                "confidence_score": 5,
                "reasoning": "Proof content is high value and monetizable, though access to customer interviews can slow delivery.",
                "next_actions": [
                    "Draft one sample customer story package",
                    "Target companies with weak testimonial pages",
                    "Offer a first customer-story sprint",
                ],
                "deliverables": [
                    "Story package sample",
                    "Prospect target list",
                    "Pilot sprint proposal",
                ],
            },
        ],
    },
    "leadgen_operator": {
        "label": "Leadgen Operator",
        "guidance": (
            "Identify profitable lead generation offers, outbound systems, or qualification workflows that create "
            "pipeline quickly."
        ),
        "fallback": {
            "niche": "AI-assisted outbound prospecting for niche B2B providers",
            "target_customer": "Local and vertical service companies with high-ticket deals",
            "core_problem": "Teams need more qualified leads but cannot maintain consistent prospecting",
            "offer": "Managed lead sourcing and qualification service",
            "mvp": "Weekly lead list with personalized outreach suggestions",
            "distribution_channel": "Cold email and partner referrals",
            "monetization_model": "Retainer plus performance bonus",
            "opportunity_score": 8,
            "confidence_score": 7,
            "reasoning": (
                "Lead generation maps directly to revenue, buyers understand the outcome, and manual support can "
                "bridge product gaps early."
            ),
            "next_actions": [
                "Pick one vertical with high customer lifetime value",
                "Assemble a sample lead list and outreach sequence",
                "Offer a two-week paid qualification sprint",
            ],
            "deliverables": [
                "Lead qualification rubric",
                "Sample outreach sequence",
                "Pilot KPI dashboard",
            ],
        },
        "fallback_opportunities": [
            {
                "title": "Outbound Qualification Sprint",
                "niche": "AI-assisted outbound prospecting for niche B2B providers",
                "target_customer": "Local and vertical service companies with high-ticket deals",
                "core_problem": "Teams need more qualified leads but cannot maintain consistent prospecting",
                "offer": "Managed lead sourcing and qualification service",
                "mvp": "Weekly lead list with personalized outreach suggestions",
                "distribution_channel": "Cold email and partner referrals",
                "monetization_model": "Retainer plus performance bonus",
                "opportunity_score": 8,
                "confidence_score": 7,
                "reasoning": "Lead generation maps directly to revenue, buyers understand the outcome, and manual support can bridge product gaps early.",
                "next_actions": [
                    "Pick one vertical with high customer lifetime value",
                    "Assemble a sample lead list and outreach sequence",
                    "Offer a two-week paid qualification sprint",
                ],
                "deliverables": [
                    "Lead qualification rubric",
                    "Sample outreach sequence",
                    "Pilot KPI dashboard",
                ],
            },
            {
                "title": "Inbound Lead Enrichment Desk",
                "niche": "Lead scoring and enrichment for inbound-heavy B2B teams",
                "target_customer": "Small SaaS companies with under-optimized inbound flows",
                "core_problem": "Teams receive leads but cannot prioritize them consistently",
                "offer": "Lead enrichment and routing service",
                "mvp": "Daily scored lead feed with recommended follow-up sequence",
                "distribution_channel": "Outbound to heads of sales",
                "monetization_model": "Monthly subscription",
                "opportunity_score": 7,
                "confidence_score": 7,
                "reasoning": "The workflow is measurable and sticky, making it a good bridge from service process to productized scoring software.",
                "next_actions": [
                    "Map the lead enrichment workflow end to end",
                    "Generate a before-and-after prioritization example",
                    "Test a paid pilot with one inbound sales team",
                ],
                "deliverables": [
                    "Scoring logic sheet",
                    "Pilot workflow diagram",
                    "Sales pitch deck",
                ],
            },
            {
                "title": "Partner List Generation Engine",
                "niche": "Channel partner discovery for B2B vendors",
                "target_customer": "Small software and service companies selling through partners",
                "core_problem": "Teams lack a repeatable way to source and rank partner opportunities",
                "offer": "Partner prospecting and ranking service",
                "mvp": "Ranked partner list with fit notes and intro strategy",
                "distribution_channel": "Founder outreach and GTM advisors",
                "monetization_model": "Project fee plus monthly upkeep",
                "opportunity_score": 6,
                "confidence_score": 6,
                "reasoning": "This solves a real GTM problem with clear deliverables, though partner success takes longer to prove than direct leadgen.",
                "next_actions": [
                    "Create a sample partner map",
                    "Choose one vertical with active channel ecosystems",
                    "Pitch a partner prospecting sprint",
                ],
                "deliverables": [
                    "Partner map sample",
                    "Vertical shortlist",
                    "Sprint offer memo",
                ],
            },
            {
                "title": "Appointment Readiness Workflow",
                "niche": "Meeting qualification support for sales teams",
                "target_customer": "Agencies and services firms booking discovery calls",
                "core_problem": "Booked meetings often lack qualification and context",
                "offer": "Pre-meeting qualification and prep service",
                "mvp": "Qualification brief delivered before every booked call",
                "distribution_channel": "Outbound to small sales teams and agencies",
                "monetization_model": "Per-meeting fee with retainer option",
                "opportunity_score": 7,
                "confidence_score": 6,
                "reasoning": "This is close to revenue and easy to test, though operational delivery can stay manual-heavy without software leverage.",
                "next_actions": [
                    "Design a meeting prep template",
                    "Offer a pilot for one sales team",
                    "Track conversion lift from better qualification",
                ],
                "deliverables": [
                    "Prep brief template",
                    "Pilot KPI tracker",
                    "Prospect outreach sequence",
                ],
            },
            {
                "title": "Local Demand Capture System",
                "niche": "Lead sourcing for location-based service businesses",
                "target_customer": "Home services and local specialist providers",
                "core_problem": "Local businesses need more leads but cannot maintain structured outbound",
                "offer": "AI-assisted local prospecting workflow",
                "mvp": "Weekly lead feed with message templates and follow-up plan",
                "distribution_channel": "Cold outreach and local business networks",
                "monetization_model": "Monthly retainer",
                "opportunity_score": 6,
                "confidence_score": 5,
                "reasoning": "Local leadgen is easy to understand and sell, but deal sizes are smaller and churn risk can be higher.",
                "next_actions": [
                    "Pick one high-value local vertical",
                    "Compile a sample week of leads",
                    "Offer a low-ticket lead supply pilot",
                ],
                "deliverables": [
                    "Sample lead sheet",
                    "Pilot pricing page",
                    "Outbound script",
                ],
            },
        ],
    },
    "product_operator": {
        "label": "Product Operator",
        "guidance": (
            "Identify profitable software or workflow-tool MVPs that solve a painful business problem and can be "
            "validated quickly."
        ),
        "fallback": {
            "niche": "Vertical AI workflow tool for ops-heavy SMB teams",
            "target_customer": "Operations managers at midsize service companies",
            "core_problem": "Teams waste time coordinating repetitive workflows across fragmented tools",
            "offer": "AI workflow copilot for one high-friction operational task",
            "mvp": "Narrow dashboard that automates task intake, triage, and reporting",
            "distribution_channel": "Founder demos to niche communities and existing operators",
            "monetization_model": "Per-seat subscription with onboarding fee",
            "opportunity_score": 7,
            "confidence_score": 6,
            "reasoning": (
                "Software can scale well, but product risk is higher than service-led modes until one workflow is "
                "validated with paying users."
            ),
            "next_actions": [
                "Choose one workflow with clear operational pain",
                "Prototype a clickable demo for that single workflow",
                "Run discovery and demo calls with five target buyers",
            ],
            "deliverables": [
                "Workflow map",
                "MVP screen list",
                "Demo script",
            ],
        },
        "fallback_opportunities": [
            {
                "title": "Workflow Copilot for Service Ops",
                "niche": "Vertical AI workflow tool for ops-heavy SMB teams",
                "target_customer": "Operations managers at midsize service companies",
                "core_problem": "Teams waste time coordinating repetitive workflows across fragmented tools",
                "offer": "AI workflow copilot for one high-friction operational task",
                "mvp": "Narrow dashboard that automates task intake, triage, and reporting",
                "distribution_channel": "Founder demos to niche communities and existing operators",
                "monetization_model": "Per-seat subscription with onboarding fee",
                "opportunity_score": 7,
                "confidence_score": 6,
                "reasoning": "Software can scale well, but product risk is higher than service-led modes until one workflow is validated with paying users.",
                "next_actions": [
                    "Choose one workflow with clear operational pain",
                    "Prototype a clickable demo for that single workflow",
                    "Run discovery and demo calls with five target buyers",
                ],
                "deliverables": [
                    "Workflow map",
                    "MVP screen list",
                    "Demo script",
                ],
            },
            {
                "title": "Client Intake Automation Tool",
                "niche": "AI-assisted client onboarding for service firms",
                "target_customer": "Agencies and consultancies with manual onboarding",
                "core_problem": "Client intake is slow, inconsistent, and drains senior team time",
                "offer": "Intake automation workspace with AI summaries",
                "mvp": "Form-to-summary tool with onboarding checklist management",
                "distribution_channel": "Founder outbound and implementation partners",
                "monetization_model": "Subscription with setup fee",
                "opportunity_score": 8,
                "confidence_score": 7,
                "reasoning": "The pain is immediate, workflows are repetitive, and a narrow product can replace obvious admin work quickly.",
                "next_actions": [
                    "Interview five firms with onboarding bottlenecks",
                    "Mock up the intake-to-summary workflow",
                    "Pilot the concierge version before coding the full UI",
                ],
                "deliverables": [
                    "Onboarding workflow map",
                    "Clickable prototype",
                    "Pilot prospect list",
                ],
            },
            {
                "title": "Proposal Generation Workbench",
                "niche": "Proposal drafting for sales-heavy service businesses",
                "target_customer": "Consultants, agencies, and custom service firms",
                "core_problem": "Teams waste time rewriting proposals and scoping documents from scratch",
                "offer": "AI proposal drafting and scope builder",
                "mvp": "Single workflow that converts discovery notes into editable proposals",
                "distribution_channel": "Outbound to agency founders and RevOps advisors",
                "monetization_model": "Seat-based subscription",
                "opportunity_score": 7,
                "confidence_score": 7,
                "reasoning": "Proposal pain is frequent and monetizable, and the output is concrete enough to validate quickly with manual support.",
                "next_actions": [
                    "Collect sample discovery notes and proposal outputs",
                    "Prototype the note-to-proposal transformation",
                    "Test willingness to pay with three agencies",
                ],
                "deliverables": [
                    "Transformation sample pack",
                    "Demo prototype",
                    "Pricing test script",
                ],
            },
            {
                "title": "Renewal Risk Monitor",
                "niche": "AI health scoring for account management teams",
                "target_customer": "Small B2B SaaS teams with churn pressure",
                "core_problem": "Teams lack an early warning system for renewal risk across accounts",
                "offer": "Renewal risk signal dashboard",
                "mvp": "Simple account health score and intervention suggestions",
                "distribution_channel": "Customer success communities and targeted outbound",
                "monetization_model": "Subscription tiered by account volume",
                "opportunity_score": 6,
                "confidence_score": 6,
                "reasoning": "The use case is valuable but requires more integration trust than simpler workflow products.",
                "next_actions": [
                    "Map the minimum health inputs needed",
                    "Create a scorecard demo using static data",
                    "Validate with customer success leads",
                ],
                "deliverables": [
                    "Health scorecard",
                    "Static demo",
                    "Validation script",
                ],
            },
            {
                "title": "Internal Knowledge Answer Tool",
                "niche": "AI knowledge assistant for operations teams",
                "target_customer": "Growing SMB teams with fragmented SOPs",
                "core_problem": "Employees lose time searching for answers across docs and chats",
                "offer": "Internal knowledge answer layer with workflow memory",
                "mvp": "Searchable internal assistant for one department’s SOPs",
                "distribution_channel": "Product-led demos and community distribution",
                "monetization_model": "Subscription per team or workspace",
                "opportunity_score": 6,
                "confidence_score": 5,
                "reasoning": "Knowledge tools are common, so the opportunity depends on strong vertical or workflow-specific differentiation.",
                "next_actions": [
                    "Choose one department with repeated SOP questions",
                    "Build a narrow assistant demo with curated content",
                    "Validate adoption with one pilot team",
                ],
                "deliverables": [
                    "Content ingestion sample",
                    "Assistant demo",
                    "Pilot adoption checklist",
                ],
            },
        ],
    },
}


def get_mode_prompt(mode: str) -> dict:
    return MODE_PROMPTS.get(mode, MODE_PROMPTS["research_operator"])


def get_fallback_opportunities(mode: str, count: int) -> list[dict]:
    prompts = get_mode_prompt(mode)
    fallback_opportunities = prompts.get("fallback_opportunities", [])
    if not fallback_opportunities:
        fallback_opportunities = [prompts["fallback"]]
    return [opportunity.copy() for opportunity in fallback_opportunities[:count]]
